---
- hosts: all
  sudo: yes
  gather_facts: no

  tasks:
    - name: nginx
      apt: name=nginx state=latest update_cache=yes

  handlers:
    - name: restart nginx
      service: name=nginx state=restarted
