---
- name: dependencies
  apt: name={{item}} state=latest update_cache=yes
  with_items:
    - python-software-properties

- name: nodejs ppa
  apt_repository: repo=ppa:chris-lea/node.js

- name: install nodejs packages
  apt: name=nodejs state=latest update_cache=yes

- name: install some global node packages
  npm: name={{item}} global=yes state=latest
  with_items:
    - jshint
    - jslint
    - js-beautify
    - grunt-cli
