---
- name: dependencies
  apt: name={{item}}
  with_items:
    - python-software-properties

- name: nodejs ppa
  apt_repository: repo=ppa:chris-lea/node.js

- name: install nodejs packages
  apt: name=nodejs update_cache=yes

- name: install some global node packages
  npm: name={{item}} global=yes
  with_items:
    - jshint
    - jslint
    - grunt-cli
