---
- name: dependencies
  apt: name={{item}}
  with_items:
    - python-pycurl
    - python-software-properties

- name: nodejs ppa
  apt_repository: repo=ppa:chris-lea/node.js

- name: install nodejs packages
  apt: name=nodejs update_cache=yes
