---
  - name: create app databases
    sudo_user: postgres
    action: postgresql_db db={{name}}{{item}} encoding='UTF-8' lc_collate='en_GB.UTF-8' lc_ctype='en_GB.UTF-8' template='template0'
    with_items:
     - ""
     - _development
     - _test

  - name: create app database user
    sudo_user: postgres
    action: postgresql_user db={{name}}{{item}} user={{name}} password={{password}} priv=ALL
    with_items:
     - ""
     - _development
     - _test

  - name: add database user privilege
    sudo_user: postgres
    action: postgresql_user user={{name}} role_attr_flags=SUPERUSER,CREATEDB
