---
- hosts: all

  tasks:
    - name: install rvm
      sudo: no
      shell: curl -L https://get.rvm.io | bash -s stable --autolibs=enabled creates=/home/vagrant/.rvm

    - name: build {{version}}
      sudo: no
      command: rvm install {{version}}
      when: version is defined
