---
- name: download deb
  get_url: url=https://googlecl.googlecode.com/files/{{googlecl}}.deb dest=/root/{{googlecl}}.deb

- name: install deps
  apt: name={{item}}
  with_items:
    - python-gdata

- name: install
  command: dpkg -i /root/{{googlecl}}.deb
