---
- name: install usual packages
  apt: name={{item}} update_cache=yes
  with_items:
    - aptitude
    - build-essential
    - git
    - git-annex
    - tig
    - vim
    - ranger
    - glances
    - htop
    - tmux
    - tree
    - ack-grep
    - exuberant-ctags
    - curl
    - keychain
    - dict
    - highlight
    - w3m
    - caca-utils
    - poppler-utils
    - atool
    - mediainfo
    - stow
    - cowsay
    - cmatrix
    - bc
    - sc
    - markdown
    - gnupg2
    - bison
    - valgrind
    - cmake
    - python-dev
    - libexpat1-dev
    - libcurl4-openssl-dev
    - html-xml-utils
    - python-pycurl
    - python-software-properties
    - software-properties-common
    - bash-completion

- name: link ack
  file: src=/usr/bin/ack-grep dest=/usr/local/bin/ack owner=root group=root state=link
