---
- name: install usual packages
  apt: name={{item}}
  with_items:
    - aptitude
    - build-essential
    - vim
    - git
    - git-annex
    - tig
    - ranger
    - htop
    - tmux
    - tree
    - ack-grep
    - exuberant-ctags
    - curl
    - keychain
    - dict
    - highlight
    - w3m
    - caca-utils
    - poppler-utils
    - atool
    - mediainfo
    - libcurl4-openssl-dev
    - stow
    - cowsay
    - markdown

- name: link ack
  file: src=/usr/bin/ack-grep dest=/usr/local/bin/ack owner=root group=root state=link

- name: ranger config
  sudo: no
  file: path=~/.config/ranger state=directory

- name: ranger copy
  sudo: no
  command: ranger --copy-config=all
