---
- include: ppa_pirho.yml
- include: ppa_gitcore.yml
- include: ide.yml
- include: rails.yml
- include: phantomjs.yml

- name: install some global node packages
  npm: name={{item}} global=yes
  with_items:
    - jshint
    - jslint
    - js-beautify
    - grunt-cli
