---
- name: silver searcher dependencies
  apt: name={{item}}
  with_items:
    - automake
    - pkg-config
    - libpcre3-dev
    - zlib1g-dev
    - liblzma-dev
    - stow

- name: clone silver searcher repo
  git: repo=https://github.com/ggreer/the_silver_searcher.git dest=/tmp/ag

- name: ensure destination dir exists
  file: path=/usr/local/stow/the_silver_searcher state=directory owner=root group=root

- name: build silver searcher
  shell: ./build.sh --prefix=/usr/local/stow/the_silver_searcher chdir=/tmp/ag

- name: install silver searcher
  shell: make install chdir=/tmp/ag creates=/usr/local/stow/the_silver_searcher/bin

- name: stow silver searcher
  shell: stow -R -d /usr/local/stow -t /usr/local the_silver_searcher
