---
- name: get the weemux repo
  git: repo=https://github.com/zolrath/wemux.git dest=/usr/local/share/wemux force=yes

- name: install wemux
  file: src=/usr/local/share/wemux/wemux dest=/usr/local/bin/wemux state=link

- name: copy config
  shell: cp -vn /usr/local/share/wemux/wemux.conf.example /usr/local/etc/wemux.conf creates=/usr/local/etc/wemux.conf

- name: remove host_list
  lineinfile: dest=/usr/local/etc/wemux.conf regexp="^host_list=" state=absent
  when: host_list is defined

- name: add host_list
  lineinfile:
    dest: /usr/local/etc/wemux.conf
    regexp: "^host_list="
    line: 'host_list=({{host_list}})'
  when: host_list is defined

